# paths
model_path: "checkpoints/no-encoder/tbd"
image_path: "../project_n/data/Original_Data_in_DICOM_Format/positive/UF160"
save_path: "data/inference/no-encoder/"

target_step_deg: 0.2

just_sr: False
