# paths
model_path: "models/checkpoint_epoch_352.pt"
patch_path: "../project_n/data/val/UF015_patch_000.npz"
output_prefix: "data/inference/newest/patch_000"

# data params
patch_size: [64, 64]
stride: [56, 56]

# reconstruction params
target_step_deg: 1.0
sampled_step_deg: 0.5
